### ISSUE TITLE
Release a new (patch) version of data

### ISSUE THREAD

**Issue by iriberri** [CartoDB/geocoder-api#78]
Due to a bug in the admin0_synonyms table creation, there was a problem with some data that we spotted in the last weeks.

The script for admin0_synonyms has been fixed, and the way to go from the initial data to this "new version" is just:

```sql
DELETE FROM admin0_synonyms WHERE rank = 8 AND char_length(name_) < 4
```

I guess this requires to give name to this new data version. Initial one was named `0.0.1`. The only file affected is `admin0_synonyms.sql`, the rest is the same.

The tasks that come to my mind to do this are:

* [ ] Create new folder in bucket for this new data version.
  Given that the changes are only on `admin0_synonyms.sql`, it would be nice to redirect to the files in `0.0.1` for the rest of dumps so that we don't occupy extra space  in the bucket for files that are literally the same.
* [ ] Create an SQL patch to migrate `0.0.1` data to this new version. (The required SQL is the line noted above).

It's the first time we need to version this afaik, so there's no really any process setup for this yet in terms of where to locate this patch and so on. Perhaps it does not even make sense to load new data in the bucket as far as we have the patch to create it, as it can be considered a "minor" version.

cc @rafatower @ethervoid

**Comment by rafatower** [comment]
is it was what applied to solve https://github.com/CartoDB/cartodb/issues/6371 @iriberri ?

**Comment by rafatower** [comment]
actually this ticket fits in the data-sources repo, as the "engine" and the api do not change

**Comment by iriberri** [comment]
Yes.

Totally, I talked about this before with @ethervoid. I was thinking totally about "fixing the API results" and my mind went here directly. Gonna close and reopen in data-services so that the patch is together with the discussion :-).
